version: "3.9"
services:
  c3_cash_register:
    image: node:18
    command: /root/product/execute.sh
    container_name: c3_cash_register
    volumes:
      - .:/root/product
    ports:
    - "3000:3000"
    env_file:
      - ./.env
    networks:
      - app-net


  db:
    image: postgres
    container_name: c3_cash_register_database
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app-net

networks:
  app-net:
    name: c3_cash_register_app_net
    driver: bridge

volumes:
  dbdata: null
